name: Deploy Extension

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      - name: Clone Sourcepawn
        run: git clone https://github.com/alliedmodders/sourcepawn.git
      - name: Setup ambuild
        working-directory: ./sourcepawn
        run: |
          git clone https://github.com/alliedmodders/ambuild.git
          pip install ./ambuild
      - name: Build
        working-directory: ./sourcepawn
        env:
          CC: emcc
          CXX: em++
          EMSCRIPTEN: $EMSDK/fastcomp/emscripten
        run: |
          mkdir objdir
          cd objdir
          python ../configure.py --enable-optimize --targets=unknown
          ambuild
