name: Deploy Extension

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      - name: Clone Sourcepawn
        run: git clone https://github.com/alliedmodders/sourcepawn.git
      - name: Setup ambuild
        working-dir: ./sourcepawn
        run: |
          git clone https://github.com/alliedmodders/ambuild.git
          pip install ./ambuild
          AM_CC=emcc
          AM_CXX=em++
          AM_ARCH=x86
          AM_TYPE=optimize
      - name: Build
        working-dir: ./sourcepawn
        run: |
          mkdir objdir
          cd objdir
          CC=$AM_CC CXX=$AM_CXX python ../configure.py --enable-$AM_TYPE --targets=$AM_ARCH
          ambuild
