name: Deploy Extension

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: mymindstorm/setup-emsdk@v11
      - run: git clone https://github.com/alliedmodders/sourcepawn.git
      - run: cd sourcepawn && git clone https://github.com/alliedmodders/ambuild.git
      - run: ls && pip install ./ambuild
